remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: NfinityParad0x aka Brian Sutterfield
description: This is a work in progress portfolio as I continue to progress down the Cybersecurity Rabbit Hole
